# Generated by Django 4.2.10 on 2024-02-22 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STRENGTH', 'Strength'), ('INTELLIGENCE', 'Intelligence'), ('AGILITY', 'Agility'), ('UNIVERSAL', 'Universal')], help_text='The name of DOTA2 the attribute.', max_length=30, unique=True, verbose_name='DOTA2 attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='DOTA2 hero name')),
                ('attack_type', models.CharField(choices=[('MELEE', 'MELEE'), ('RANGE', 'RANGE')], max_length=7, unique=True, verbose_name='DOTA2 attack type')),
                ('main_attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.attribute', verbose_name='DOTA2 hero main attribute')),
            ],
        ),
    ]
