# Generated by Django 4.2.10 on 2024-02-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='DOTA2 ability')),
                ('description', models.TextField(verbose_name='DOTA2 ability description')),
            ],
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(choices=[('STRENGTH', 'Strength'), ('INTELLIGENCE', 'Intelligence'), ('AGILITY', 'Agility'), ('UNIVERSAL', 'Universal')], help_text='The name of DOTA2 the attribute.', max_length=16, unique=True, verbose_name='DOTA2 attribute'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='attack_type',
            field=models.CharField(choices=[('MELEE', 'MELEE'), ('RANGE', 'RANGE')], max_length=8, unique=True, verbose_name='DOTA2 hero attack type'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='DOTA2 hero name'),
        ),
        migrations.AddField(
            model_name='hero',
            name='abilities',
            field=models.ManyToManyField(to='polls.ability', verbose_name='DOTA2 hero abilities'),
        ),
    ]
