# Generated by Django 4.2.10 on 2024-03-05 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_hero_melody'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='DOTA2 item name')),
                ('description', models.TextField(verbose_name='DOTA2 item description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='Item Image')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.AlterField(
            model_name='hero',
            name='melody',
            field=models.FileField(blank=True, null=True, upload_to='melodies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])], verbose_name='Melody'),
        ),
    ]
