# Generated by Django 4.2.10 on 2024-03-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_item_alter_hero_melody'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('PASSIVE', 'PASSIVE'), ('ACTIVE', 'ACTIVE')], default='default', max_length=10, unique=True, verbose_name='DOTA2 item type'),
            preserve_default=False,
        ),
    ]
